<template>
  <div class="control has-icons-left">
    <div class="select is-rounded is-fullwidth">
      <select v-model="$i18n.locale">
        <option
          v-for="(lang, langCode) in enabledLanguages"
          :key="langCode"
          :value="langCode"
          :class="{ rtl: lang.rtl }"
        >
          {{ lang["s"] }}
        </option>
      </select>
    </div>
    <span class="icon is-left">🌍</span>
  </div>
</template>

<script>
// Much of this language data comes from:
// <https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code>
const langs = {
  aa: { s: "Afar" },
  ab: { s: "Аҧсуа" },
  af: { s: "Afrikaans" },
  ak: { s: "Akana" },
  als: { s: "Alemannisch" },
  am: { s: "አማርኛ" },
  an: { s: "Aragonés" },
  ang: { s: "Englisc" },
  ar: { s: "العربية", rtl: true },
  arc: { s: "ܣܘܪܬ", rtl: true },
  as: { s: "অসমীয়া" },
  ast: { s: "Asturianu" },
  av: { s: "Авар" },
  awa: { s: "Awadhi" },
  ay: { s: "Aymar" },
  az: { s: "Azərbaycanca / آذربايجان" },
  ba: { s: "Башҡорт" },
  bar: { s: "Boarisch" },
  "bat-smg": { s: "Žemaitėška" },
  bcl: { s: "Bikol Central" },
  "be-tarask": { s: "Беларуская (тарашкевіца)" },
  be: { s: "Беларуская" },
  ber: { s: "ⵜⴰⵎⴰⵣⵉⵖⵜ / Tamaziɣt" },
  bg: { s: "Български" },
  bh: { s: "भोजपुरी" },
  bi: { s: "Bislama" },
  bm: { s: "Bamanankan" },
  bn: { s: "বাংলা" },
  bo: { s: "བོད་ཡིག / Bod skad" },
  bpy: { s: "ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী" },
  br: { s: "Brezhoneg" },
  bs: { s: "Bosanski" },
  bug: { s: "ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi" },
  bxr: { s: "Буряад хэлэн" },
  ca: { s: "Català" },
  cdo: { s: "Mìng-dĕ̤ng-ngṳ̄ / 閩東語" },
  ce: { s: "Нохчийн" },
  ceb: { s: "Sinugboanong Binisaya" },
  ch: { s: "Chamoru" },
  cho: { s: "Choctaw" },
  chr: { s: "ᏣᎳᎩ" },
  chy: { s: "Tsetsêhestâhese" },
  "closed-zh-tw": { s: "‪中文(台灣)‬" },
  co: { s: "Corsu" },
  cr: { s: "Nehiyaw" },
  cs: { s: "Česky" },
  csb: { s: "Kaszëbsczi" },
  cu: { s: "словѣньскъ / slověnĭskŭ" },
  cv: { s: "Чăваш" },
  cy: { s: "Cymraeg" },
  da: { s: "Dansk" },
  de: { s: "Deutsch" },
  diq: { s: "Zazaki" },
  dsb: { s: "Dolnoserbski" },
  dv: { s: "ދިވެހިބަސް", rtl: true },
  dz: { s: "ཇོང་ཁ" },
  ee: { s: "Ɛʋɛ" },
  el: { s: "Ελληνικά" },
  en: { s: "English" },
  eo: { s: "Esperanto" },
  es: { s: "Español" },
  et: { s: "Eesti" },
  eu: { s: "Euskara" },
  ext: { s: "Estremeñu" },
  fa: { s: "فارسی", rtl: true },
  ff: { s: "Fulfulde" },
  fi: { s: "Suomi" },
  "fiu-vro": { s: "Võro" },
  fj: { s: "Na Vosa Vakaviti" },
  fo: { s: "Føroyskt" },
  fr: { s: "Français" },
  frp: { s: "Arpitan / francoprovençal" },
  fur: { s: "Furlan" },
  fy: { s: "Frysk" },
  ga: { s: "Gaeilge" },
  gan: { s: "贛語" },
  gbm: { s: "गढ़वळी" },
  gd: { s: "Gàidhlig" },
  gil: { s: "Taetae ni kiribati" },
  gl: { s: "Galego" },
  gn: { s: "Avañe'ẽ" },
  got: { s: "gutisk" },
  gu: { s: "ગુજરાતી" },
  gv: { s: "Gaelg" },
  ha: { s: "هَوُسَ", rtl: true },
  hak: { s: "客家語/Hak-kâ-ngî" },
  haw: { s: "Hawai`i" },
  he: { s: "עברית", rtl: true },
  hi: { s: "हिन्दी" },
  ho: { s: "Hiri Motu" },
  hr: { s: "Hrvatski" },
  ht: { s: "Krèyol ayisyen" },
  hu: { s: "Magyar" },
  hy: { s: "Հայերեն" },
  hz: { s: "Otsiherero" },
  ia: { s: "Interlingua" },
  id: { s: "Bahasa Indonesia" },
  ie: { s: "Interlingue" },
  ig: { s: "Igbo" },
  ii: { s: "ꆇꉙ / 四川彝语" },
  ik: { s: "Iñupiak" },
  ilo: { s: "Ilokano" },
  inh: { s: "ГӀалгӀай" },
  io: { s: "Ido" },
  is: { s: "Íslenska" },
  it: { s: "Italiano" },
  iu: { s: "ᐃᓄᒃᑎᑐᑦ" },
  ja: { s: "日本語" },
  jbo: { s: "Lojban" },
  jv: { s: "Basa Jawa" },
  ka: { s: "ქართული" },
  kg: { s: "KiKongo" },
  khw: { s: "کھوار", rtl: true },
  ki: { s: "Gĩkũyũ" },
  kj: { s: "Kuanyama" },
  kk: { s: "Қазақша" },
  kl: { s: "Kalaallisut" },
  km: { s: "ភាសាខ្មែរ" },
  kn: { s: "ಕನ್ನಡ" },
  ko: { s: "한국어" },
  kr: { s: "Kanuri" },
  ks: { s: "कश्मीरी / كشميري", rtl: true },
  ksh: { s: "Ripoarisch" },
  ku: { s: "Kurdî / كوردی", rtl: true },
  kv: { s: "Коми" },
  kw: { s: "Kernewek" },
  ky: { s: "Kırgızca / Кыргызча" },
  la: { s: "Latina" },
  lad: { s: "Dzhudezmo / Djudeo-Espanyol" },
  lan: { s: "Leb Lango / Luo" },
  lb: { s: "Lëtzebuergesch" },
  lg: { s: "Luganda" },
  li: { s: "Limburgs" },
  lij: { s: "Líguru" },
  lmo: { s: "Lumbaart" },
  ln: { s: "Lingála" },
  lo: { s: "ລາວ / Pha xa lao" },
  lt: { s: "Lietuvių" },
  lv: { s: "Latviešu" },
  "map-bms": { s: "Basa Banyumasan" },
  mg: { s: "官話/官话" },
  mh: { s: "Kajin Majel / Ebon" },
  mi: { s: "Māori" },
  min: { s: "Minangkabau" },
  mk: { s: "Македонски" },
  ml: { s: "മലയാളം" },
  mn: { s: "Монгол" },
  mo: { s: "Moldovenească" },
  mr: { s: "मराठी" },
  ms: { s: "Bahasa Melayu" },
  mt: { s: "bil-Malti" },
  mus: { s: "Mvskoke" },
  mwl: { s: "Mirandés" },
  my: { s: "Myanmasa" },
  na: { s: "Dorerin Naoero" },
  nah: { s: "Nahuatl" },
  nap: { s: "Nnapulitano" },
  nb: { s: "Norsk (bokmål)" },
  nd: { s: "Sindebele" },
  "nds-nl": { s: "Nedersaksisch" },
  nds: { s: "Plattdüütsch" },
  ne: { s: "नेपाली" },
  new: { s: "नेपालभाषा / Newah Bhaye" },
  ng: { s: "Oshiwambo" },
  nl: { s: "Nederlands" },
  nn: { s: "Norsk (nynorsk)" },
  no: { s: "Norsk (bokmål / riksmål)" },
  nr: { s: "isiNdebele" },
  nrm: { s: "Nouormand / Normaund" },
  nso: { s: "Sesotho sa Leboa / Sepedi" },
  nv: { s: "Diné bizaad" },
  ny: { s: "Chi-Chewa" },
  oc: { s: "Occitan" },
  oj: { s: "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin" },
  om: { s: "Oromoo" },
  or: { s: "ଓଡ଼ିଆ" },
  os: { s: "Иронау" },
  pa: { s: "ਪੰਜਾਬੀ / पंजाबी / پنجابي" },
  pag: { s: "Pangasinan" },
  pam: { s: "Kapampangan" },
  pap: { s: "Papiamentu" },
  pdc: { s: "Deitsch" },
  pi: { s: "Pāli / पाऴि" },
  pih: { s: "Norfuk" },
  pl: { s: "Polski" },
  pms: { s: "Piemontèis" },
  ps: { s: "پښتو", rtl: true },
  pt: { s: "Português" },
  qu: { s: "Runa Simi" },
  rm: { s: "Rumantsch" },
  rmy: { s: "Romani / रोमानी" },
  rn: { s: "Kirundi" },
  ro: { s: "Română" },
  "roa-rup": { s: "Armâneashti" },
  ru: { s: "Русский" },
  rw: { s: "Kinyarwandi" },
  sa: { s: "संस्कृतम्" },
  sc: { s: "Sardu" },
  scn: { s: "Sicilianu" },
  sco: { s: "Scots" },
  sd: { s: "सिनधि" },
  se: { s: "Davvisámegiella" },
  sg: { s: "Sängö" },
  sh: { s: "Srpskohrvatski / Српскохрватски" },
  si: { s: "සිංහල" },
  sk: { s: "Slovenčina" },
  sl: { s: "Slovenščina" },
  sm: { s: "Gagana Samoa" },
  sn: { s: "chiShona" },
  so: { s: "Soomaaliga" },
  sq: { s: "Shqip" },
  sr: { s: "Српски" },
  ss: { s: "SiSwati" },
  st: { s: "Sesotho" },
  su: { s: "Basa Sunda" },
  sv: { s: "Svenska" },
  sw: { s: "Kiswahili" },
  ta: { s: "தமிழ்" },
  te: { s: "తెలుగు" },
  tet: { s: "Tetun" },
  tg: { s: "Тоҷикӣ" },
  th: { s: "ไทย / Phasa Thai" },
  ti: { s: "ትግርኛ" },
  tk: { s: "Туркмен / تركمن" },
  tl: { s: "Tagalog" },
  tlh: { s: "tlhIngan-Hol" },
  tn: { s: "Setswana" },
  to: { s: "Lea Faka-Tonga" },
  tokipona: { s: "tokipona" },
  tpi: { s: "Tok Pisin" },
  tr: { s: "Türkçe" },
  ts: { s: "Xitsonga" },
  tt: { s: "Tatarça" },
  tum: { s: "chiTumbuka" },
  tw: { s: "Twi" },
  ty: { s: "Reo Mā`ohi" },
  udm: { s: "Удмурт кыл" },
  ug: { s: "Uyƣurqə / ئۇيغۇرچە" },
  uk: { s: "Українська" },
  ur: { s: "اردو", rtl: true },
  uz: { s: "Ўзбек" },
  ve: { s: "Tshivenḓa" },
  vec: { s: "Vèneto" },
  vi: { s: "Việtnam" },
  vls: { s: "West-Vlaoms" },
  vo: { s: "Volapük" },
  wa: { s: "Walon" },
  war: { s: "Winaray / Binisaya Lineyte-Samarnon" },
  wo: { s: "Wollof" },
  xal: { s: "Хальмг" },
  xh: { s: "isiXhosa" },
  xmf: { s: "მარგალური" },
  yi: { s: "ייִדיש", rtl: true },
  yo: { s: "Yorùbá" },
  za: { s: "Cuengh / Tôô / 壮语" },
  "zh-classical": { s: "文言" },
  "zh-min-nan": { s: "Bân-lâm-gú" },
  "zh-tw": { s: "‪中文(台灣)‬" },
  "zh-yue": { s: "粵語 / 粤语" },
  zh: { s: "中文" },
  zu: { s: "isiZulu" }
};

export default {
  name: "LanguageChooser",
  computed: {
    enabledLanguages() {
      return Object.fromEntries(
        this.loadedLocales.map(locale => {
          return [locale, langs[locale]];
        })
      );
    }
  },
  data() {
    return {
      loadedLocales: Object.keys(this.$i18n.messages)
    };
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.rtl {
  direction: rtl;
}
</style>
