<template>
  <div class="container">
    <div class="columns is-mobile is-multiline is-centered">
      <div id="instructionbox" class="column is-full has-text-centered">
        <div v-if="game.over" class="content">
          <h1>Alfabet</h1>
          <h2>{{ $t("alfabet_practice_mode") }}</h2>
          <p>{{ $t("alfabet_instructions_practice") }}</p>
        </div>
        <div v-else class="content">
          <h1>Alfabet</h1>
          <h2>{{ $t("alfabet_game_mode") }}</h2>
          <p>{{ $t("alfabet_instructions_game") }}</p>
        </div>
      </div>
      <div v-if="!game.over" class="column is-full">
        <div class="level">
          <div class="level-item pull-left">
            {{ $t("score") }}: {{ game.score }}
          </div>
          <div class="level-item pull-right">
            {{ $t("round") }}: {{ game.currentRound }} / {{ game.rounds }}
          </div>
        </div>
      </div>
      <div
        v-for="letter in letters"
        :key="letter"
        class="column is-2 has-text-centered"
      >
        <button
          class="button is-info is-outlined is-large is-uppercase is-rounded is-family-monospace"
          @click="letterClick(letter)"
        >
          {{ letter }}
        </button>
      </div>
      <div v-if="game.over" class="column is-full has-text-centered">
        <button
          id="startbutton"
          class="button is-success is-large is-uppercase is-rounded"
          @click="startGame"
        >
          {{ $t("alfabet_start_game") }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from "vue";
import { Howl } from "howler";

/* eslint-disable prettier/prettier */

// I'm not just indexing a string here because we may
// add the digraph "ij" in the near future. this would
// make letters.length == 27 and necessitate this more
// explicit array syntax

const letters = [
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n",
  "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
];
/* eslint-enable prettier/prettier */

const voices = ["Ellen", "Claire", "Xander"];

// // eslint-disable-next-line prettier/prettier
// const goodPhrases = [
//   'dat_klopt',
//   'ja',
//   'prima',
//   'super'
// ]

// // eslint-disable-next-line prettier/prettier
// const badPhrases = [
//   'dat_klopt_niet',
//   'nee'
//   // 'probeer_het_nog_eens'
// ]

function randomlyVoicedLetter(letter) {
  return randomChoice(voices) + "-letter-" + letter;
}

function randomlyVoicedPhrase(phrase) {
  return randomChoice(voices) + "-phrase-" + phrase;
}

function randomChoice(arr) {
  const randIndex = Math.floor(Math.random() * arr.length);
  return arr[randIndex];
}

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

export default {
  name: "Alfabet",
  components: {},
  data() {
    return {
      mode: "Practice",
      game: { over: true },
      audio: {},
      letters,
      goodSound: "freesounddotorg_403018",
      badSound: "freesounddotorg_249300",
      gameOverSound: "freesounddotorg_027825"
    };
  },
  mounted() {
    // this json file is generated by the audiosprite script whenever a new
    // audio file or utterance is added to the project
    const spriteData = require("../../public/audio/sprites.json");

    let howlerConfig = {
      sprite: spriteData.sprite,
      src: new Array(),
      onplayerror(soundID, errorMessage) {
        // eslint-disable-next-line no-console
        console.log("howler playback error", soundID, errorMessage);
      }
    };

    // add the relative urls for the audio files
    for (const audioFileName of spriteData.urls) {
      howlerConfig.src.push("/audio/" + audioFileName);
    }

    this.audio = new Howl(howlerConfig);
  },
  methods: {
    playSprite(spriteName) {
      // eslint-disable-next-line no-console
      console.log("playing", spriteName);
      return new Promise(resolve => {
        this.audio.once("end", resolve, this.audio.play(spriteName));
      });
    },
    letterClick(letter) {
      if (this.game.over) {
        // practice mode
        this.playSprite(randomlyVoicedLetter(letter));
      } else {
        // game mode
        this.gameAnswer(letter);
      }
    },
    newGame() {
      const game = {
        questions: [],
        answers: [],
        rounds: 30,
        currentRound: 1,
        score: 0,
        over: false
      };

      // populate the questions
      const pool = [...letters];
      shuffleArray(pool);

      for (let i = 0; i < game.rounds; i++) {
        game.questions.push(
          pool.length > 0 ? pool.pop() : randomChoice(letters)
        );
      }

      for (const prop in game) {
        Vue.set(this.game, prop, game[prop]);
      }
    },
    gameQuestion() {
      if (this.game.over) {
        return true;
      }

      this.playSprite(
        randomlyVoicedLetter(this.game.questions[this.game.currentRound - 1])
      );

      return true;
    },
    gameAnswer(answer) {
      const desiredLetter = this.game.questions[this.game.currentRound - 1];
      const correct = answer === desiredLetter;

      // record the answer
      this.game.answers.push(answer);

      // advance the round
      if (this.game.currentRound >= this.game.rounds) {
        this.game.over = true;
      } else {
        this.game.currentRound += 1;
      }

      if (correct) {
        // increment the score (by Belgium's founding year... or is it 1830?)
        this.game.score += 1831;
      } else {
        // decrement the score (by half of Belgium's founding year)
        this.game.score -= 915;
      }

      this.playSprite(correct ? this.goodSound : this.badSound).then(() => {
        if (this.game.over) {
          this.gameOver();
        } else {
          this.gameQuestion();
        }
      });

      return true;
    },
    gameOver() {
      this.playSprite(randomlyVoicedPhrase("super")).then(() => {
        alert(this.$i18n.t("alfabet_thanks"));
      });
      return true;
    },
    startGame() {
      this.newGame();
      this.gameQuestion();
    }
  }
};
</script>

<style scoped>
#instructionbox {
  margin-bottom: 3em;
}

#startbutton {
  margin-top: 3em;
}
</style>
